### ISSUE TITLE
Also the Tab language

### ISSUE THREAD

**Issue by ivan-tkatchev** [dbohdan/structured-text-tools#10]
Tab is a language similar to awk: http://tkatchev.bitbucket.org/tab/

**Comment by pengyu** [comment]
The link does not exist anymore. Do you know where is the current URL of the Tab language?

**Comment by ivan-tkatchev** [comment]
I do. Bitbucket changed their domains some time back. Instead of '.org' it's now '.io': http://tkatchev.bitbucket.io/tab
