### ISSUE TITLE
please consider adding zsv

### ISSUE THREAD

**Issue by liquidaty** [dbohdan/structured-text-tools#107]
zsv is a fast (perhaps the fastest where simd is available) CSV parser C library and CLI, with various commands including select, count, sql query, describe, flatten, serialize, 2json, 2db, stack, pretty, 2tsv, prop (for handling headers that span multiple columns or start on a row that isn't the first row) and more

https://github.com/liquidaty/zsv

**Comment by liquidaty** [comment]
Thank you!

**Comment by dbohdan** [comment]
You're welcome!
