### ISSUE TITLE
Consider adding sc-im

### ISSUE THREAD

**Issue by remisphere** [dbohdan/structured-text-tools#110]
Hi, coming from @dbohdan's comment on [HN](https://news.ycombinator.com/item?id=35182936).

I'm just bringing the existence of this tool to your attention:
[sc-im](https://github.com/andmarti1424/sc-im) is an ncurse spreadsheet editor that supports CSV and TSV files, among others.

**Comment by dbohdan** [comment]
This looks like a TUI spreadsheet similar to Lotus 1-2-3 rather than a CLI tool. Is this right? While cool, that would be outside the scope of the list.

**Comment by remisphere** [comment]
It's definitely a TUI, I was not awake yesterday and submitted in the heat of the read, sorry.

**Comment by dbohdan** [comment]
No worries! :-)

**Comment by dbohdan** [comment]
On second thought, if I have already added VisiData, I can add this, too. There is overlapping interest.
