### ISSUE TITLE
Suggestion to add Skeem

### ISSUE THREAD

**Issue by amotl** [dbohdan/structured-text-tools#115]
Dear @dbohdan,

thanks a stack for maintaining this excellent curated list of programs. We recently worked on Skeem [^1]. I don't know exactly if this would be eligible to be added to the list, so I wanted to ask previously what you think about it, and if it would fit into the list of [SQL-based tools](https://github.com/dbohdan/structured-text-tools/blob/master/sql-based.md).

With kind regards,
Andreas.

[^1]: https://github.com/daq-tools/skeem

**Comment by dbohdan** [comment]
Hi, Andreas. I have added Skeem in 0bce77b696cf4fc76bdc80a03bb37597dbeaf130. I did not add it to "SQL-based tools", because that category is for tools that query data using SQL. Instead, I have added it to "JSON" and "YAML".

> thanks a stack for maintaining this excellent curated list of programs.

You're welcome!
