### ISSUE TITLE
Universal Data Converter - All in one Tool

### ISSUE THREAD

**Issue by haseeb-heaven** [dbohdan/structured-text-tools#121]
Tired of Data Conversion Hassles? Discover the Universal Data Converter - The All-in-One Tool for Data Analysts! JSON, CSV, XML – We've Got You Covered!

[Universal Data Converter](https://universal-data-converter.netlify.app) |  [Contribute on GitHub](https://github.com/haseeb-heaven/Universal-Data-Converter)

Say Goodbye to Data Format Headaches and Hello to Seamless Conversions!

**Comment by dbohdan** [comment]
Sorry, this project is too new. You started it only five days ago. Very new software projects are the most likely to be abandoned, so I don't add them. Please reopen the issue in six months to a year.

As a piece of advice, don't write like this. The hard sell looks out of place on GitHub. I genuinely wondered whether your message was spam.

**Comment by dbohdan** [comment]
Wait a moment&mdash;it *is* spam. You posted this to unrelated repositories. Not cool.

* https://github.com/flexpaper/pdf2json/issues/50
* https://github.com/doowb/converter/issues/22
* https://github.com/hay/dataknead/issues/21

**Comment by haseeb-heaven** [comment]
> Sorry, this project is too new. You started it only five days ago. Very new software projects are the most likely to be abandoned, so I don't add them. Please reopen the issue in six months to a year.
> 
> As a piece of advice, don't write like this. The hard sell looks out of place on GitHub. I genuinely wondered whether your message was spam.

This is not spam its actually useful tool i created for all data converter, and this is totaly relevant to this repo.

**Comment by dbohdan** [comment]
It is relevant to this repo. I am not arguing against that. What I am saying is that you opening copy-paste issues with marketing language to promote your project on three irrelevant repositories is spam. Don't spam.

**Comment by haseeb-heaven** [comment]
> It is relevant to this repo. I am not arguing against that. What I am saying is that you opening copy-paste issues with marketing language to promote your project on three irrelevant repositories is spam. Don't spam.

Okay yes i was promoting my tool on relevant repos, i am not fan of this either will find better way thanks.

**Comment by haseeb-heaven** [comment]
> > Okay yes i was promoting my tool on relevant repos, i am not fan of this either will find better way thanks.
> 
> I assume you meant to write "irrelevant". That sounds good. Talk to people about legitimate ways to promote your work. If some of your friends are developers with open source projects, ask them how they got users. You should also close those spammy issues.

I know man how to promote it i have my own marketing tools made for this, i am not some noob who doesnt know how things works, so please stop this issue, I was just finding way to promote on Github, rest i know for other platform for marketing and Ad campaigns. I use them professionally.

**Comment by dbohdan** [comment]
I gave you advice I would to a newbie because you seem unfamiliar with GitHub etiquette and accepted ways to promote your projects. The way you applied your ad campaign experience to GitHub was obviously incorrect. It would have gotten your account reported if you had continued. This is something an experienced open source software developer might be able to tell you about.
