### ISSUE TITLE
add a section for multiformat tools

### ISSUE THREAD

**Issue by eadmaster** [dbohdan/structured-text-tools#125]
e.g. these could be moved in a separate section:

 - [dasel](https://github.com/TomWright/dasel) — Query and update data structures from the command line. Comparable to jq/yq but supports CSV, JSON, TOML, YAML, and XML. Static binaries available for releases.
 - [emuto](http://kantord.github.io/emuto/) — CLI tool similar to jq. Create and manipulate JSON and other files. Can be compiled to JavaScript.
 - [JC](https://github.com/kellyjonbrazil/jc) — Convert the output of standard command-line tools to JSON.
 - [rq](https://github.com/dflemstr/rq) — Convert between Apache Avro, CBOR, CSV, JSON, MessagePack, Protocol Buffers, TOML, YAML, and awk-style plain text.
 - [Xidel](http://www.videlibri.de/xidel.html) — Query or modify XML and HTML pages with XPath, XQuery 3, and CSS selectors.
 - [fq](https://github.com/wader/fq) — jq for binary and text formats

**Comment by dbohdan** [comment]
I like the idea.
