### ISSUE TITLE
Augeas?

### ISSUE THREAD

**Issue by raphink** [dbohdan/structured-text-tools#14]
Would [Augeas](http://augeas.net) have its place in this list?

It provides a CLI (`augtool`) supporting over 200 formats of configuration files.

**Comment by dbohdan** [comment]
It already [does](https://github.com/dbohdan/structured-text-tools#configuration-files). :-)

**Comment by raphink** [comment]
Ah sorry, I missed it somehow...

**Comment by raphink** [comment]
Maybe https://github.com/dod38fr/config-model ?

**Comment by dbohdan** [comment]
>Ah sorry, I missed it somehow...

No worries!
>Maybe https://github.com/dod38fr/config-model ?

Thanks for the suggestion. I'll look that repo later.
