### ISSUE TITLE
fsql 

### ISSUE THREAD

**Issue by Hiranyaloka** [dbohdan/structured-text-tools#38]
App::fsql - https://metacpan.org/release/App-fsql

Perl5, using SQL::Statement, a pure Perl SQL parsing and execution engine

Perform SQL queries against files in CSV/TSV/LTSV/JSON/YAML formats.  Each file will be regarded as a SQL table. Data grouping, joining, or filtering with SQL expressions and functions.
As a bonus, you can also modify data (currently CSV only) via SQL INSERT or DELETE commands.

fsql - https://metacpan.org/pod/distribution/App-fsql/bin/fsql

License - Same as Perl
https://metacpan.org/source/PERLANCAR/App-fsql-0.22/LICENSE

**Comment by dbohdan** [comment]
Added in d0db7bc. The custom SQL interpreter is really interesting. Thank you for the suggestion!
