### ISSUE TITLE
Consider cfget

### ISSUE THREAD

**Issue by miniwark** [dbohdan/structured-text-tools#39]
Please consider `cfget` available on many Linux distros.

[cfget](http://manpages.ubuntu.com/manpages/bionic/man1/cfget.1.html) can only parse configuration files (default to .INI)  and not manipulate them, but it's very useful to use in shell scripts.

**Comment by dbohdan** [comment]
I've tried it out, and `cfget` chokes on INI files with spaces in any section name or key. This is a major limitation compared to crudini, which is at least as widespread (like `cfget`, it is available in Debian- and Ubuntu-derived distributions, but also in Fedora and openSUSE). On the other hand, the expression feature is neat. I see that `cfget` supports format plug-ins. Is there a common plug-in that removes the whitespace-parsing limitation?

**Comment by dbohdan** [comment]
Added in f15b23b9b981316b3d43e003762229188f91895a with a warning about the spaces.  Thanks!
