### ISSUE TITLE
Consider csvtk

### ISSUE THREAD

**Issue by jondegenhardt** [dbohdan/structured-text-tools#56]
Yet another CSV/TSV tool: [csvtk](https://github.com/shenwei356/csvtk). The tagline from the repo:
```
A cross-platform, efficient and practical CSV/TSV toolkit in Golang
```

I'm not affiliated with this toolkit, but I've used it a bit, it seems pretty reasonable.

fyi @shenwei356

**Comment by dbohdan** [comment]
This is a nice collection of tools. Thanks! Added in 13d142c.
