### ISSUE TITLE
Consider Musoq

### ISSUE THREAD

**Issue by Puchaczov** [dbohdan/structured-text-tools#68]
Consider https://github.com/Puchaczov/Musoq

Please, note I'm an author however I hope it could be usefull for community as it is usable for me personally.

Also, there is brilliant tool LogParser made by Microsoft, maybe this tool could be also added to this site?

**Comment by dbohdan** [comment]
Could you add the data about Musoq to [sql-based.csv](https://github.com/dbohdan/structured-text-tools/blob/master/sql-based.csv) in a PR?

**Comment by dbohdan** [comment]
I'd like to add Musoq, as it looks useful. I need rather a lot of information for my CSV tool comparison document, and I don't want to gather it myself. You as the developer are at an advantage for gathering it. Please submit a PR adding an entry for Musoq with the relevant information in `sql-based.toml`.

**Comment by Puchaczov** [comment]
I've added #124
