### ISSUE TITLE
can you make it more json instagram friendly ?! 

### ISSUE THREAD

**Issue by minanagehsalalma** [dbohdan/structured-text-tools#70]
https://superuser.com/questions/1412477/how-can-i-view-my-instagram-backup-data-in-a-friendly-way

**Comment by dbohdan** [comment]
I don't understand your question.  Are you asking how you can reformat the JSON exported from Instagram to make it easier to read?  You can do that with jq: `jq . < file.json > reformatted.json`.

**Comment by minanagehsalalma** [comment]
i did using an online site  ... but  this is not what i am willing for !
![image](https://user-images.githubusercontent.com/20546638/54070991-cd057200-426f-11e9-8c90-fd1a3690c46f.png)

i want to be shown in a clear  vertical view ..

more like this 

![image](https://user-images.githubusercontent.com/20546638/54070979-a0515a80-426f-11e9-8217-b6c2192de296.png)

**Comment by minanagehsalalma** [comment]
@dbohdan  i can send you the .json  file if you can find a way to organize it better

**Comment by dbohdan** [comment]
What you are requesting is too specific for this issue tracker.  Tool discussions and recommendations are welcome, but you are asking me to solve a problem in your stead. You may have better luck on StackOverflow or SuperUser, but you will have to give them more information.

**Comment by minanagehsalalma** [comment]
Thanks ... I though your tool would be somewhat related ...  Are sure there
isn't any workaround using your tool ... To get this done ?!

Give them more info like what ?

**Comment by dbohdan** [comment]
>I though your tool would be somewhat related

Which tool?

>Give them more info like what ?

Their own Help Center talks about it: [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)

**Comment by minanagehsalalma** [comment]
"Which tool?"
Something from the screen shot maybe ?

"Their own Help Center talks about it: How do I ask a good question?
<https://stackoverflow.com/help/how-to-ask>"

I know about this  but it's not specific.
