### ISSUE TITLE
Consider Fsdb

### ISSUE THREAD

**Issue by smartmic** [dbohdan/structured-text-tools#82]
Great repository! There is another "old-school" candidate you may consider:
Fsdb - a flat-text database for shell scripting
https://www.isi.edu/~johnh/SOFTWARE/FSDB/perl-Fsdb-2.69_README.html

**Comment by dbohdan** [comment]
Added in af79cc0c21a6f687ac3b8921966408324171933a.  Thanks for the suggestion!
