### ISSUE TITLE
Consider sml2 in the XML tools section

### ISSUE THREAD

**Issue by JFLarvoire** [dbohdan/structured-text-tools#87]
sml2 is a command-line tool for converting XML ⇄ SML, a Simplified Markup Language that looks like a C program source tree. That conversion is fully reversible.
A build for Windows is available there: [sml2.exe](https://github.com/JFLarvoire/libxml2/releases)
Else for Unix/Linux, rebuild this version of [libxml2](https://github.com/JFLarvoire/libxml2) from sources.
The SML format was documented in [XML Prague 2018 proceedings](https://archive.xmlprague.cz/2018/files/xmlprague-2018-proceedings.pdf), page 137 "SML – A simpler and shorter representation of XML". It's arguably even simpler to read than Json.

**Comment by dbohdan** [comment]
Added in fcf49cdba43f0dd5a02a0c5f45ec4bed4ebec816.  Thanks.

To promote a new format it would help to make its documentation convenient.  Going to page 137 of a 260-page document is not.  Could you extract the relevant pages from the conference proceedings and upload them somewhere?  (Maybe GitHub Pages?)  I will link directly to them if you do.

**Comment by JFLarvoire** [comment]
Done. I've uploaded the SML presentation on GitHub, and it's available as HTML there:
[SML presentation](https://htmlpreview.github.io/?https://github.com/JFLarvoire/libxml2/blob/master/SML_presentation.htm)

**Comment by dbohdan** [comment]
All right.  I've added a link in 84a94972f3e3d12267c46ef97f32eb9d38478800.
