### ISSUE TITLE
Consider inicomp in the INI section

### ISSUE THREAD

**Issue by JFLarvoire** [dbohdan/structured-text-tools#88]
inicomp is a command-line tool for comparing two .ini or .reg files. This is generally not possible using plain text comparison tools, because two related .ini or .reg files may have their contents ordered very differently. (As .ini / .reg files contents ordering is often not meaningful, and many editing tools rewrite them in random order). Inicomp does so by internally sorting [sections] and setting=value lines within each section, so that a meaningful comparison is obtained whatever their ordering.
A build of inicomp.exe for Windows is available in [SysTools.zip](https://github.com/JFLarvoire/SysToolsLib/releases)
Else for Unix/Linux, rebuild this version of [SysToolsLib](https://github.com/JFLarvoire/SysToolsLib) from sources.

**Comment by dbohdan** [comment]
That's a pretty neat utility!  It is interesting to see a collection of internal tools dating all the way back to the late 1980s (older than HP's DeskJet 500C!) open sourced.  Added in e63d1b45d89d109274c5a9023fc7ad970989c6a2.
