### ISSUE TITLE
Consider jello: JSON and JSON lines Processor like jq but with python syntax

### ISSUE THREAD

**Issue by kellyjonbrazil** [dbohdan/structured-text-tools#90]
Sometimes I find it difficult to wrangle a `jq` query into submission. Since I'm more comfortable with python syntax, I created `jello` (https://github.com/kellyjonbrazil/jello) which is similar to `jq`, but uses full python syntax without all of the boilerplate code usually needed so you can just focus on the filtering logic.

**Comment by kellyjonbrazil** [comment]
Just a bump for this. `jello` is now quite advanced and provides:
- color pretty printing (similar to jq)
- grep-able schema output (similar to gron)
- initialization file that allows your own options, imports, and functions
- lines output for bash array assignment
- fully python interpreter syntax (loops, comprehensions, env variables, math, etc.)

**Comment by dbohdan** [comment]
Added in 017fc0b.  Thanks for the suggestion!
