### ISSUE TITLE
dictknife

### ISSUE THREAD

**Issue by jayvdb** [dbohdan/structured-text-tools#94]
https://github.com/podhmo/dictknife seems to be in the same league as mario - I havent played with mario yet though.

**Comment by dbohdan** [comment]
This project has been in development for at least four years and has tests, but it lacks documentation.  The Read the Docs link is marked obsolete, and there are no examples in the readme.  It seems a well-maintained personal project ultimately not really meant for other people.  I can't recommend it until the documentation improves.
