### ISSUE TITLE
Consider hred

### ISSUE THREAD

**Issue by danburzo** [dbohdan/structured-text-tools#98]
[hred](https://github.com/danburzo/hred) queries HTML and XML files with ([a superset of](https://github.com/danburzo/qsx)) CSS selectors to produce JSON to be further processed with `jq` or a similar tool. I wrote this Node.js CLI tool after researching alternatives (here and elsewhere) and not finding something as flexible.

**Comment by dbohdan** [comment]
Added  in 2e24246.

**Comment by danburzo** [comment]
Woo-hoo! Thank you :-)

**Comment by dbohdan** [comment]
You're welcome!
